### ISSUE TITLE
free github runner space in container env

### ISSUE THREAD

**Issue by wuwentao** [jlumbroso/free-disk-space#21]
hello @jlumbroso 

we are using github public runner to build image with our container, as this container installed all of our build tools and env, so we want to do build job in container as below:

```
build_image:
    name: Build
    runs-on: [ubuntu-latest]
    timeout-minutes: 180
    container:
      image: ghcr.io/kendryte/k230_sdk:latest
      env:
        CONF: k230_${{ matrix.cfg }}_defconfig
      options: --hostname release --user root
    steps:

```

then we meet the  ERROR `No space left on device` in github runner .

any suggestion or solution to free disk space with this container build env ?

Thanks
Wentao
