### ISSUE TITLE
Perf improvement: disable man-db before removing

### ISSUE THREAD

**Issue by lachesis** [jlumbroso/free-disk-space#40]
When run like this, we save more than a minute, from 5:21 runtime to 4:12.
```
    - name: Disable man-db to make package install and removal faster
      run: |
        echo 'set man-db/auto-update false' | sudo debconf-communicate >/dev/null
        sudo dpkg-reconfigure man-db

    - name: Free Disk Space (Ubuntu) # Attempting to get around 16gb space limitations when building CUDA
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: true
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        swap-storage: true
```
I'm not sure why Github decided to keep the man-db enabled in CI by default. See [this issue](https://github.com/actions/runner-images/issues/10977).
